2023-03-24 08:18:29.344 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:18:39.429 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:18:49.524 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:18:59.631 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:19:09.725 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:19:19.835 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:19:29.932 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:19:40.115 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:19:50.431 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:20:01.016 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:20:12.125 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:20:24.230 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:20:38.437 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:20:56.735 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:21:23.224 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:22:03.323 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:22:43.414 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:23:23.533 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:24:03.624 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:24:43.732 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:25:23.832 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:26:03.915 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:26:44.019 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:27:24.117 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:28:04.228 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:28:44.317 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:29:24.417 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:30:04.521 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:30:44.622 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:31:24.729 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:32:04.822 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
2023-03-24 08:32:44.928 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.1.17:6379
